(function(){
'use strict';
const C=window.VesperCore,$=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch{return false;}}};
let savedSettings={};try{savedSettings=JSON.parse(storage.get('vesper-settings')||'{}')||{};}catch{}
const settings=Object.assign({quality:'medium',scale:.85,fov:57,limit:60,sound:.3,mouse:.85,invert:false},savedSettings);
settings.limit=[30,60,120].includes(Number(settings.limit))?Number(settings.limit):60;
let renderer;try{renderer=new window.VesperRenderer($('#space'));renderer.setSettings(settings);}catch(e){$('#load-error').hidden=false;$('#load-error').textContent='Не удалось запустить 3D: '+e.message+'. Открой игру в актуальном Chrome, Edge или Firefox с включённым аппаратным ускорением.';return;}
let world=C.createWorld(),myId='solo',mode='menu',ws=null,networkState='idle',lastSnapshot=0,serverOffset=0,currentPanel=null,hangarTab='service',lastNotice=0,saveTimer=0,drawTimer=0,netTimer=0,lastFrame=performance.now(),accumulator=0,fps=60,lastHull=150,transientMouse={yaw:0,pitch:0},keys={},mouseFire=false,touch={},padPrevious=[],padDetected=false,snapshotPrev=null,snapshotNow=null,snapshotTime=0,sessionResume=null;
let audioCtx=null,engineOsc=null,engineGain=null,lastShot=0,storageWarned=false;
$('#pilot-name').value=storage.get('vesper-pilot')||'Странник';
const p=()=>world.players[myId];
function toast(message,error=false){const node=document.createElement('div');node.className='toast'+(error?' error':'');node.textContent=message;$('#notifications').appendChild(node);while($('#notifications').children.length>3)$('#notifications').firstElementChild.remove();setTimeout(()=>node.remove(),5500);}
function audioStart(){if(!settings.sound)return;try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();engineOsc=audioCtx.createOscillator();engineGain=audioCtx.createGain();engineOsc.type='sawtooth';engineOsc.frequency.value=38;const low=audioCtx.createBiquadFilter();low.type='lowpass';low.frequency.value=160;engineOsc.connect(low);low.connect(engineGain);engineGain.connect(audioCtx.destination);engineGain.gain.value=0;engineOsc.start();}audioCtx.resume();}catch{}}
function beep(type='shot'){if(!audioCtx||!settings.sound)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type=type==='shot'?'triangle':'sine';o.frequency.setValueAtTime(type==='shot'?650:220,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(type==='shot'?110:660,audioCtx.currentTime+.15);g.gain.setValueAtTime(settings.sound*.12,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.18);o.start();o.stop(audioCtx.currentTime+.2);}
function startUI(){document.body.classList.add('playing');$('#start').hidden=true;$('#planet-caption').hidden=true;$('#menu-footer').hidden=true;$('#hud').hidden=false;$('#interface').style.background='transparent';lastNotice=0;lastHull=p()?.hull||150;lastPvp=world.pvp;audioStart();drawHUD();}
function startSolo(){disconnect();mode='solo';myId='solo';const saved=storage.get('vesper-save');try{world=saved?C.restoreWorld(JSON.parse(saved)):C.createWorld();}catch{world=C.createWorld();toast('Сохранение не удалось прочитать. Создан новый полёт.',true);}if(!world.players.solo)world.players.solo=C.createPlayer('solo',$('#pilot-name').value);world.players.solo.name=$('#pilot-name').value.trim()||'Странник';world.players={solo:world.players.solo};world.pvp=false;storage.set('vesper-pilot',p().name);closePanel();startUI();toast(p().notice);}
function disconnect(){if(ws){ws.onclose=null;ws.onerror=null;ws.close();ws=null;}networkState='idle';snapshotPrev=snapshotNow=null;}
function saveSolo(){if(mode!=='solo')return;if(!storage.set('vesper-save',JSON.stringify(C.snapshot(world)))&&!storageWarned){storageWarned=true;toast('Автосохранение недоступно. Скачай сохранение в меню паузы.',true);}}
function returnMenu(){saveSolo();disconnect();closePanel();mode='menu';keys={};document.exitPointerLock?.();$('#start').hidden=false;$('#planet-caption').hidden=false;$('#menu-footer').hidden=false;$('#hud').hidden=true;document.body.classList.remove('playing','jumping');$('#mode-label').textContent='ЛОКАЛЬНЫЙ СЕКТОР';$('#interface').style.background='';if(engineGain)engineGain.gain.value=0;}
function act(a){if(mode==='solo'){C.action(world,myId,a);saveSolo();observe();drawHUD();}else if(mode==='multi'&&ws?.readyState===1){ws.send(JSON.stringify({type:'action',action:a}));}if(a.type==='land'&&p()?.landed)beep('land');}
function observe(){const me=p();if(!me)return;if(me.noticeSeq!==lastNotice){if(me.notice)toast(me.notice);lastNotice=me.noticeSeq;}if(me.hull<lastHull){$('#damage-vignette').classList.add('hit');setTimeout(()=>$('#damage-vignette').classList.remove('hit'),250);beep('hit');}lastHull=me.hull;if(currentPanel==='hangar')refreshHangar();}
function panel(title,section,body,wide=true){document.exitPointerLock?.();keys={};mouseFire=false;transientMouse={yaw:0,pitch:0};renderer.closePreview();$('#panel-content').innerHTML='<div class="panel-head"><div><div class="eyebrow">'+section+'</div><h2>'+title+'</h2></div><button id="close-panel" aria-label="Закрыть">×</button></div>'+body;$('#panel').style.width=wide?'min(1040px,94vw)':'min(680px,94vw)';if(!$('#panel').open)$('#panel').showModal();$('#close-panel').onclick=closePanel;}
function closePanel(){if($('#panel').open)$('#panel').close();currentPanel=null;renderer.closePreview();keys={};touch={};}
$('#panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});
function settingsPanel(){currentPanel='settings';panel('Настройки полёта','VESPER / КОНФИГУРАЦИЯ','<div class="panel-body"><div class="settings-grid"><div class="setting"><label for="quality">КАЧЕСТВО ГРАФИКИ</label><select id="quality"><option value="low">Низкое — меньше деталей</option><option value="medium">Среднее — баланс</option><option value="high">Высокое — полный сектор</option></select><small>Меняет число звёзд, астероиды и атмосферу.</small></div><div class="setting"><label for="resolution">РАЗРЕШЕНИЕ РЕНДЕРА</label><select id="resolution"><option value="0.5">50% — производительность</option><option value="0.67">67%</option><option value="0.85">85% — сбалансированное</option><option value="1">100% — чёткость</option></select><small id="resolution-info">Интерфейс сохраняет полную чёткость.</small></div><div class="setting"><label for="fps-limit">ЧАСТОТА КАДРОВ</label><select id="fps-limit"><option value="30">30 FPS</option><option value="60">60 FPS</option><option value="120">120 FPS</option></select></div><div class="setting"><label for="fov">УГОЛ ОБЗОРА — <span id="fov-value"></span>°</label><input id="fov" type="range" min="45" max="90" step="1"></div><div class="setting"><label for="sound">ГРОМКОСТЬ — <span id="sound-value"></span>%</label><input id="sound" type="range" min="0" max="1" step="0.05"></div><div class="setting"><label for="mouse">ЧУВСТВИТЕЛЬНОСТЬ МЫШИ</label><input id="mouse" type="range" min="0.2" max="2" step="0.1"><small>Щелчок по космосу включает обзор мышью.</small></div><label class="check"><input type="checkbox" id="invert">Инверсия вертикальной оси</label><div class="muted" id="gamepad-status">'+(padDetected?'Геймпад подключён · стандартная раскладка':'Геймпад: подключи и нажми любую кнопку')+'</div></div><div class="panel-actions"><button id="apply-settings" class="primary">Применить</button><button id="fullscreen">Полный экран</button>'+(mode!=='menu'?'<button id="pause-open">Меню полёта</button>':'')+'</div></div>',false);
 $('#quality').value=settings.quality;$('#resolution').value=settings.scale;$('#fps-limit').value=settings.limit;$('#fov').value=settings.fov;$('#sound').value=settings.sound;$('#mouse').value=settings.mouse;$('#invert').checked=settings.invert;const labels=()=>{$('#fov-value').textContent=$('#fov').value;$('#sound-value').textContent=Math.round($('#sound').value*100);};labels();$('#fov').oninput=labels;$('#sound').oninput=labels;
 $('#apply-settings').onclick=()=>{Object.assign(settings,{quality:$('#quality').value,scale:Number($('#resolution').value),limit:Number($('#fps-limit').value),fov:Number($('#fov').value),sound:Number($('#sound').value),mouse:Number($('#mouse').value),invert:$('#invert').checked});renderer.setSettings(settings);storage.set('vesper-settings',JSON.stringify(settings));audioStart();closePanel();toast('Настройки применены · '+$('#space').width+' × '+$('#space').height);};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('Полноэкранный режим недоступен в этом окне.'));};if($('#pause-open'))$('#pause-open').onclick=pausePanel;
}
function helpPanel(){currentPanel='help';panel('До встречи на орбите','ИНСТРУКТАЖ / 02 МИНУТЫ','<div class="panel-body help-grid"><div><h3>Первый маршрут</h3><ol><li>Начни одиночный полёт. Нажми <kbd>E</kbd>, чтобы сесть на Аврору.</li><li>Нажми <kbd>F</kbd>: через 5 секунд найдёшь тайник с валютой.</li><li><kbd>K</kbd> откроет ангар. Собери корабль, заправь бак и выбери оружие.</li><li><kbd>E</kbd> — взлёт. <kbd>M</kbd> — карта и переход к другой планете за 22 топлива.</li><li>Красные метки — пираты. За уничтожение получишь 180 CR.</li></ol><div class="inline-note">Пустой бак останавливает корабль. <kbd>T</kbd> вызывает заправщик и аварийный ремонт двигателя. Бесплатно, если денег не хватает.</div><h3 style="margin-top:24px">DualSense / геймпад</h3><p>Левый стик — тяга и стрейф; правый — поворот. R2 — огонь, L2 — тормоз, R1 — форсаж. ✕ — посадка, △ — поиск, □ — оружие, ○ — помощь. D-pad ↑/↓ — высота; ← — карта; → — ангар. Options — пауза.</p><p class="muted">Подключи по USB или Bluetooth и нажми кнопку. Нужна стандартная раскладка Gamepad API; поддержка зависит от ОС и браузера. Вибрация и адаптивные триггеры не используются.</p></div><div><h3>Клавиатура и мышь</h3><table class="control-table"><tbody>'+[['W / S','Тяга вперёд / назад'],['A / D','Боковые двигатели'],['↑ / ↓ / ← / →','Поворот корабля'],['C / Ctrl','Подъём / снижение'],['Q / Z','Крен'],['Shift','Форсаж'],['X','Тормоз'],['Пробел / ЛКМ','Стрельба'],['R / 1 / 2','Переключить орудие'],['E','Посадка / взлёт'],['F','Поиск тайников на планете'],['T','Заправщик / ремонт двигателя'],['M / K','Карта / ангар'],['Esc','Пауза / отпустить мышь']].map(([k,v])=>'<tr><td><kbd>'+k+'</kbd></td><td>'+v+'</td></tr>').join('')+'</tbody></table><p class="muted" style="margin-top:18px">Щелчок по космосу захватывает мышь. Для выхода нажми Esc. Лазер не требует патронов, но перегревается. Щит восстанавливается через 5 секунд без попаданий. Одиночный полёт приостановлен в меню; онлайн-мир продолжает жить.</p></div></div>');}
function multiplayerPanel(){currentPanel='multiplayer';const sameHost=location.protocol==='http:'||location.protocol==='https:';const defaultURL=sameHost?(location.protocol==='https:'?'wss://':'ws://')+location.host:'ws://localhost:8080';panel('Собрать звено','МУЛЬТИПЛЕЕР / ДО 8 ПИЛОТОВ','<div class="panel-body"><p>Один игрок запускает сервер. Остальные открывают его адрес в браузере и заходят в одну комнату.</p><div class="form-grid"><div><label for="server-url">АДРЕС СЕРВЕРА</label><input id="server-url" placeholder="ws://192.168.1.10:8080" value="'+escape(storage.get('vesper-server')||defaultURL)+'"></div><div class="two"><div><label for="room">КОМНАТА</label><input id="room" value="'+escape(storage.get('vesper-room')||'friends')+'" maxlength="24" pattern="[A-Za-z0-9_-]+"></div><div><label for="room-pass">ПАРОЛЬ КОМНАТЫ</label><input id="room-pass" type="password" maxlength="64" placeholder="Задаёт первый пилот"></div></div><div><label for="multi-name">ПОЗЫВНОЙ</label><input id="multi-name" maxlength="20" value="'+escape($('#pilot-name').value||'Странник')+'"></div><label class="check"><input type="checkbox" id="pvp">Разрешить бой между игроками (при создании комнаты)</label><div class="inline-note">На компьютере хоста: <code>docker compose up --build -d</code><br>Для друзей в локальной сети: <code>http://IP_ХОСТА:8080</code><br>По умолчанию — совместная игра против пиратов. На HTTPS-странице нужен <code>wss://</code>. Для локального сервера открой его HTTP-адрес.</div><div id="connect-error" class="error-text" role="status"></div><button id="connect" class="primary">Подключиться к комнате <span>↗</span></button></div></div>',false);$('#connect').onclick=connectFromForm;}
function connectFromForm(){const error=$('#connect-error'),room=$('#room').value.trim().toLowerCase(),name=$('#multi-name').value.trim()||'Странник';let url=$('#server-url').value.trim();url=url.replace(/^http:/,'ws:').replace(/^https:/,'wss:');let parsed;try{parsed=new URL(url);}catch{error.textContent='Введи полный адрес, например ws://192.168.1.10:8080';return;}if(!['ws:','wss:'].includes(parsed.protocol)){error.textContent='Адрес должен начинаться с ws:// или wss://';return;}if(location.protocol==='https:'&&parsed.protocol==='ws:'&&!['localhost','127.0.0.1'].includes(parsed.hostname)){error.textContent='Открой http://'+parsed.host+' и подключись там, либо используй сервер с wss://.';return;}if(!/^[a-z0-9_-]{1,24}$/.test(room)){error.textContent='Комната: 1–24 латинские буквы, цифры, _ или -.';return;}parsed.pathname='/ws';parsed.search='';parsed.hash='';sessionResume={url:parsed.toString(),room,name,password:$('#room-pass').value,pvp:$('#pvp').checked};storage.set('vesper-server',url);storage.set('vesper-room',room);storage.set('vesper-pilot',name);error.textContent='Соединение с сервером…';$('#connect').disabled=true;connect(sessionResume);}
function connect(conf){disconnect();networkState='connecting';const resumeKey='vesper-session-'+conf.url+'-'+conf.room;try{ws=new WebSocket(conf.url);}catch(e){connectionError(e.message);return;}const socket=ws;let welcomed=false;const timeout=setTimeout(()=>{if(!welcomed){connectionError('Сервер не ответил. Проверь адрес, порт 8080 и запущен ли Docker.');socket.close();}},9000);
 socket.onopen=()=>{socket.send(JSON.stringify({type:'join',room:conf.room,password:conf.password,name:conf.name,pvp:conf.pvp,token:storage.get(resumeKey)}));};
 socket.onmessage=e=>{let data;try{data=JSON.parse(e.data);}catch{return;}if(data.type==='error'){clearTimeout(timeout);connectionError(data.message);socket.close();return;}if(data.type==='welcome'){welcomed=true;clearTimeout(timeout);myId=data.id;storage.set(resumeKey,data.token);mode='multi';networkState='online';world=data.world;snapshotNow=world;snapshotPrev=null;lastSnapshot=performance.now();snapshotTime=lastSnapshot;closePanel();startUI();toast('Комната '+conf.room+' · '+(world.pvp?'PvP включён':'совместный полёт'));return;}if(data.type==='snapshot'&&welcomed){snapshotPrev=snapshotNow;snapshotNow=data.world;world=data.world;lastSnapshot=performance.now();snapshotTime=lastSnapshot;networkState='online';observe();}};
 socket.onerror=()=>{if(!welcomed)connectionError('Не удалось подключиться. Проверь адрес сервера и разрешение порта 8080.');};socket.onclose=()=>{clearTimeout(timeout);if(socket!==ws)return;if(welcomed){networkState='lost';toast('Связь с сервером потеряна. Полёт на сервере сохранён.',true);drawHUD();}else if(networkState==='connecting')connectionError('Сервер закрыл соединение. Проверь настройки комнаты.');};
}
function connectionError(message){networkState='error';if($('#connect-error'))$('#connect-error').textContent=message;else toast(message,true);if($('#connect'))$('#connect').disabled=false;}
let lastPvp=false;
function pausePanel(){if(mode==='menu')return settingsPanel();currentPanel='pause';panel('Полет продолжается','VESPER / '+(mode==='solo'?'СОЛО НА ПАУЗЕ':'ОНЛАЙН — МИР НЕ ПРИОСТАНОВЛЕН'),'<div class="panel-body"><div class="menu-options"><button class="primary" id="resume">Вернуться в кабину</button><button data-panel="settings">Графика и управление</button><button data-panel="help">Краткий инструктаж</button>'+(mode==='solo'?'<button id="export-save">Скачать сохранение</button><button id="import-save">Загрузить сохранение</button><input type="file" id="save-file" accept="application/json,.json" hidden>':'<div class="inline-note">Комната: '+escape(sessionResume?.room||'')+' · '+Object.keys(world.players).length+' пилотов<br>'+(world.pvp?'Бой между игроками разрешён.':'Огонь по союзникам отключён.')+'</div>')+'<button id="return-menu">Завершить полёт</button></div></div>',false);$('#resume').onclick=closePanel;$('#return-menu').onclick=returnMenu;if($('#export-save'))$('#export-save').onclick=()=>{saveSolo();const blob=new Blob([JSON.stringify(C.snapshot(world),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vesper-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Сохранение скачано.');};if($('#import-save')){$('#import-save').onclick=()=>$('#save-file').click();$('#save-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2e6){toast('Файл слишком большой.',true);return;}try{const restored=C.restoreWorld(JSON.parse(await f.text()));if(!restored.players.solo)throw new Error('Нет одиночного пилота');world=restored;world.players={solo:world.players.solo};world.pvp=false;saveSolo();closePanel();toast('Полёт восстановлен.');}catch{toast('Этот файл не является сохранением VESPER.',true);}};}}
function mapPanel(){if(!p()){toast('Сначала начни полёт.');return;}currentPanel='map';const me=p(),nearest=C.nearest(me),coords=[[215,220],[350,120],[95,100],[235,38]];const svg='<svg class="system-map" viewBox="0 0 440 360" role="img" aria-label="Карта четырёх планет системы"><path class="map-grid" d="M20 180H420M220 15V340"/><ellipse class="map-orbit" cx="220" cy="180" rx="105" ry="67"/><ellipse class="map-orbit" cx="220" cy="180" rx="155" ry="109"/><ellipse class="map-orbit" cx="220" cy="180" rx="205" ry="156"/><circle class="star" cx="220" cy="180" r="5"/><text x="232" y="183">ГЕЛИОС</text>'+C.PLANETS.map((pl,i)=>'<circle cx="'+coords[i][0]+'" cy="'+coords[i][1]+'" r="'+(nearest.planet.id===pl.id?12:7)+'" fill="'+pl.color+'" fill-opacity=".13" stroke="'+pl.color+'"/><circle cx="'+coords[i][0]+'" cy="'+coords[i][1]+'" r="3" fill="'+pl.color+'"/><text x="'+(coords[i][0]+17)+'" y="'+(coords[i][1]+4)+'">'+pl.name+'</text>').join('')+'</svg>';
 panel('Система Гелиос','НАВИГАЦИЯ / ЧЕТЫРЕ МИРА','<div class="panel-body map-layout"><div>'+svg+'<div class="inline-note">Квантовый переход: <b>22 топлива</b> · 6 секунд.<br>Сначала взлети. Нужны исправные двигатель и реактор (от 25%).</div><p class="map-note">Можно долететь и обычной тягой. Кольца показывают схему маршрутов, расстояния указаны справа.</p></div><div class="planet-list">'+C.PLANETS.map((pl,i)=>'<button class="planet-card" data-jump="'+pl.id+'"><span class="eyebrow" style="color:'+pl.color+'">0'+(i+1)+' / '+escape(pl.type)+'</span><h3>'+pl.name+(nearest.planet.id===pl.id?' <span class="tag">ВЫ ЗДЕСЬ</span>':'')+'</h3><p>'+pl.port+' · тайники от '+pl.reward+' CR</p><div class="row"><span>'+formatDistance(C.dist(me.p,pl.p))+'</span><span>'+(nearest.planet.id===pl.id&&nearest.alt<1800?'Текущая орбита':me.landed?'Сначала взлети':'Переход ↗')+'</span></div></button>').join('')+'</div></div>');document.querySelectorAll('[data-jump]').forEach(el=>el.onclick=()=>{act({type:'jump',planet:el.dataset.jump});if(mode==='multi'||p().jump)closePanel();});}
let hangarSignature='';
function hangarPanel(){const me=p();if(!me?.landed){toast('Ангар доступен после посадки. Подлети к планете и нажми E.');return;}currentPanel='hangar';const pl=C.PLANETS.find(x=>x.id===me.landed);panel('Ангар · '+pl.port,'ОБСЛУЖИВАНИЕ / СБОРКА / ВООРУЖЕНИЕ','<div class="hangar-grid"><div class="ship-column"><div class="ship-title"><b>Скиталец / '+escape(me.name)+'</b><span class="tag">MK. I</span></div><canvas id="ship-preview" aria-label="Вращающаяся 3D-модель вашего корабля"></canvas><div id="ship-stats" class="ship-stats"></div><label>ЦВЕТ КОРПУСА</label><div class="paint-row">'+C.COLORS.map((c,i)=>'<button aria-label="Цвет '+['белый','оранжевый','бирюзовый','сиреневый','зелёный'][i]+'" style="background:'+c+'" data-paint="'+c+'"></button>').join('')+'</div><label>БОРТОВАЯ НАКЛЕЙКА · БЕСПЛАТНО</label><div class="decal-row">'+C.DECALS.map((d,i)=>'<button data-decal="'+d+'">'+['Нет','Комета','Шеврон','Череп','Солнце'][i]+'</button>').join('')+'</div><p class="muted" style="margin-top:20px">Шесть модульных отсеков. Добавленные и снятые блоки меняют вид и характеристики корабля.</p></div><div class="hangar-content"><div class="row" style="margin-bottom:20px"><span class="muted">Счёт пилота</span><span class="credits" id="hangar-credits"></span></div><nav class="tab-strip" aria-label="Разделы ангара"><button data-tab="service">Сервис</button><button data-tab="modules">Конструктор</button><button data-tab="weapons">Оружие</button></nav><div id="hangar-tab"></div></div></div>');renderer.openPreview($('#ship-preview'),me);hangarSignature='';document.querySelectorAll('[data-paint]').forEach(b=>b.onclick=()=>act({type:'paint',color:b.dataset.paint}));document.querySelectorAll('[data-decal]').forEach(b=>b.onclick=()=>act({type:'decal',decal:b.dataset.decal}));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{hangarTab=b.dataset.tab;renderHangarTab();});renderHangarTab();refreshHangar();}
function refreshHangar(){const me=p();if(!me||!$('#hangar-credits'))return;if(!me.landed){closePanel();return;}const s=C.stats(me);$('#hangar-credits').textContent=Math.floor(me.credits).toLocaleString('ru')+' CR';$('#ship-stats').innerHTML=[['Корпус',Math.ceil(me.hull)+' / '+s.hull],['Топливо',Math.ceil(me.fuel)+' / '+s.fuel],['Скорость',s.speed+' м/с'],['Грузовой бонус','×'+s.loot]].map(([a,b])=>'<div><small>'+a+'</small><b>'+b+'</b></div>').join('');document.querySelectorAll('[data-paint]').forEach(b=>b.classList.toggle('selected',b.dataset.paint===me.color));document.querySelectorAll('[data-decal]').forEach(b=>b.classList.toggle('selected',b.dataset.decal===me.decal));const sig=JSON.stringify([me.modules,me.weapons,me.color,me.decal]);if(hangarSignature!==sig){if(hangarSignature)renderer.openPreview($('#ship-preview'),me);hangarSignature=sig;renderHangarTab();}if(hangarTab==='service'){const details=$('#service-live');const repairPrice=$('#repair-price');if(repairPrice)repairPrice.textContent=Math.ceil((s.hull-me.hull)*.35+(300-me.parts.engine-me.parts.weapons-me.parts.reactor)*.2)+' CR';if(details)details.textContent='Снаряды: '+me.ammo.shell+' · Плазма: '+me.ammo.plasma+' · Двигатель '+Math.ceil(me.parts.engine)+'% · Оружие '+Math.ceil(me.parts.weapons)+'% · Реактор '+Math.ceil(me.parts.reactor)+'%';}}
function renderHangarTab(){const me=p();if(!me||!$('#hangar-tab'))return;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===hangarTab));const content=$('#hangar-tab');if(hangarTab==='service'){const s=C.stats(me),repair=Math.ceil((s.hull-me.hull)*.35+(300-me.parts.engine-me.parts.weapons-me.parts.reactor)*.2);content.innerHTML='<p class="muted" id="service-live"></p>'+[['fuel','Топливо','До 50 единиц за визит. 1 CR за единицу.','До 50 CR','Заправить'],['shell','Кинетические снаряды','50 снарядов для рельсовой и картечной пушек.','60 CR','Пополнить'],['plasma','Плазменные заряды','50 зарядов для плазмомёта.','80 CR','Пополнить'],['repair','Ремонт и щиты','Восстановление корпуса, двигателя, реактора и оружия.',repair+' CR','Восстановить']].map(([id,title,desc,price,btn])=>'<div class="market-card"><h4>'+title+'</h4><p>'+desc+'</p><div class="row"><span '+(id==='repair'?'id="repair-price"':'')+'>'+price+'</span><button data-buy="'+id+'">'+btn+'</button></div></div>').join('')+'<p class="muted" style="margin-top:18px">Мало валюты? Закрой ангар и нажми F — поиск тайника на планете.</p>';content.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{act({type:'buy',item:b.dataset.buy});if(mode==='solo')renderHangarTab();});}
 else if(hangarTab==='modules'){content.innerHTML='<p class="muted">Снятый блок возвращает 50% цены. Удаление бака или брони уменьшает вместимость.</p>'+C.SLOTS.map((name,i)=>'<div class="module-slot"><div class="row"><span>'+name+'</span><small>ОТСЕК 0'+(i+1)+'</small></div><div class="module-action"><select aria-label="'+name+'" id="slot-'+i+'"><option value="">Пустой отсек</option>'+Object.entries(C.MODULES).map(([k,m])=>'<option value="'+k+'" '+(me.modules[i]===k?'selected':'')+'>'+m.name+' · '+m.price+' CR</option>').join('')+'</select><button data-module="'+i+'">Установить</button></div><div class="muted" style="font-size:11px;margin-top:5px">'+(C.MODULES[me.modules[i]]?.description||'Доступен для строительства')+'</div></div>').join('');content.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>act({type:'module',slot:Number(b.dataset.module),module:$('#slot-'+b.dataset.module).value||null}));}
 else{content.innerHTML='<p class="muted">Левый пилон: '+C.WEAPONS[me.weapons[0]].name+'<br>Правый пилон: '+C.WEAPONS[me.weapons[1]].name+'<br>R переключает активное орудие в полёте.</p><div class="weapons-grid">'+Object.entries(C.WEAPONS).map(([key,w])=>'<div class="weapon-card"><h4 style="color:'+w.color+'">'+w.name+'</h4><p>Урон '+(key==='scatter'?'5 × ':'')+w.damage+' · '+(1/w.cool).toFixed(1)+' выстр./с · '+(w.ammo==='shell'?'снаряды':w.ammo==='plasma'?'плазменные заряды':'без боеприпасов, перегрев')+'</p><div class="row"><span class="tag">'+(me.owned.includes(key)?'КУПЛЕНО':w.price+' CR')+'</span><button data-weapon="'+key+'" data-slot="0">Левый</button><button data-weapon="'+key+'" data-slot="1">Правый</button></div></div>').join('')+'</div>';content.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>act({type:'weapon',slot:Number(b.dataset.slot),weapon:b.dataset.weapon}));}}
function openPanel(which){if(which==='settings')settingsPanel();if(which==='help')helpPanel();if(which==='map')mapPanel();if(which==='hangar')hangarPanel();if(which==='pause')pausePanel();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(b)openPanel(b.dataset.panel);});$('.brand').onclick=e=>{e.preventDefault();mode==='menu'?closePanel():pausePanel();};$('#solo').onclick=startSolo;$('#multi').onclick=multiplayerPanel;
function formatDistance(n){return n>=1000?(n/1000).toFixed(1)+' км':Math.max(0,Math.round(n))+' м';}
const bar=(label,value,max,color='')=>'<div class="resource"><div class="row"><span>'+label+'</span><b>'+Math.ceil(value)+' / '+max+'</b></div><div class="bar '+color+'"><span style="width:'+C.clamp(value/max*100,0,100)+'%"></span></div></div>';
let hudPointerHeld=false;document.addEventListener('pointerdown',e=>{if(e.target.closest('#hud button'))hudPointerHeld=true;});document.addEventListener('pointerup',()=>hudPointerHeld=false);document.addEventListener('pointercancel',()=>hudPointerHeld=false);
function drawHUD(){if(hudPointerHeld)return;const me=p();if(mode==='menu'||!me)return;const s=C.stats(me),n=C.nearest(me),w=C.WEAPONS[me.weapons[me.active]],speed=C.len(me.v),friends=Object.keys(world.players).length;$('#mode-label').textContent=mode==='solo'?'СОЛО · АВТОСОХРАНЕНИЕ':(sessionResume?.room||'')+' · '+friends+'/8 · '+(world.pvp?'PVP':'CO-OP');document.body.classList.toggle('jumping',!!me.jump);
 const objective=me.landed?'Найди тайник на поверхности':me.fuel<=0?'Вызови аварийный заправщик':me.parts.engine<=0?'Вызови аварийный ремонт':me.visited.length<2?'Исследуй следующий мир':'Заработай на новый модуль';const hint=me.landed?(me.scan?'Сканирование: '+Math.ceil(me.scan)+' с':me.scanCD?'Новый поиск: '+Math.ceil(me.scanCD)+' с':'F — сканировать местность'):me.fuel<=0||me.parts.engine<=0?'T — помощь за 10 секунд':'E — посадка · M — карта системы';
 let html='<div class="hud-top"><div class="sector-label">СИСТЕМА ГЕЛИОС / '+(me.landed?'ПОВЕРХНОСТЬ':'СВОБОДНЫЙ ПОЛЁТ')+'</div><h2 class="planet-name">'+n.planet.name+'</h2><div class="hud-distance">'+(me.landed?n.planet.port:'ВЫСОТА '+formatDistance(n.alt))+' · <span style="color:#adddd5">'+Math.floor(me.credits).toLocaleString('ru')+' CR</span></div><div class="mission"><div class="eyebrow">ЖУРНАЛ ЭКСПЕДИЦИИ</div><p>'+objective+'</p><small>'+hint+'</small></div></div><div class="flight-nav"><button data-panel="map">Карта <kbd>M</kbd></button><button data-panel="hangar">Ангар <kbd>K</kbd></button><button data-panel="help">Инструктаж <kbd>?</kbd></button></div>';
 if(!me.landed&&!me.dead&&!me.jump)html+='<div class="reticle"></div>';
 html+='<div id="targets"></div><div class="bottom-hud"><section class="hud-block"><h3>СКИТАЛЕЦ / '+escape(me.name.toUpperCase())+'</h3>'+bar('КОРПУС',me.hull,s.hull,me.hull/s.hull<.35?'red':'')+bar('ЩИТ',me.shield,s.shield)+'</section><section class="telemetry"><div class="heading-ticks"><span>270</span><span>285</span><span>'+((Math.round(-me.yaw*180/Math.PI)+360)%360).toString().padStart(3,'0')+'°</span><span>015</span><span>030</span></div><div class="speed">'+Math.round(speed)+'<small>М/С</small></div><div class="speed-caption">'+(me.landed?'ПОСАДКА ЗАВЕРШЕНА':me.rescue?'ЗАПРАВЩИК · '+Math.ceil(me.rescue)+' С':speed>s.speed?'ФОРСАЖ':'ИНЕРЦИАЛЬНЫЙ ПОЛЁТ')+'</div>'+bar('ТОПЛИВО',me.fuel,s.fuel,me.fuel<20?'red':'orange')+'</section><section class="hud-block system-info"><h3>ОРУДИЕ 0'+(me.active+1)+' / '+(me.active===0?'ЛЕВЫЙ':'ПРАВЫЙ')+' ПИЛОН</h3><div class="weapon-name">'+w.name+'</div><div class="weapon-meta">'+(w.ammo?'БОЕЗАПАС '+me.ammo[w.ammo]+' · ':'ЭНЕРГИЯ · ')+'НАГРЕВ '+Math.round(me.heat)+'%</div>'+Object.entries(me.parts).map(([k,v])=>'<div class="system-row"><span>'+({engine:'ДВИГАТЕЛЬ',weapons:'ОРУЖИЕ',reactor:'РЕАКТОР'}[k])+'</span><b class="'+(v<35?'broken':'')+'">'+(v<=0?'ОТКАЗ':Math.ceil(v)+'%')+'</b></div>').join('')+'</section></div><div class="key-strip"><span><kbd>W S</kbd> Тяга</span><span><kbd>↑ ↓ ← →</kbd> Поворот</span><span><kbd>Space</kbd> Огонь</span><span><kbd>E</kbd> '+(me.landed?'Взлёт':'Посадка')+'</span><span class="extra"><kbd>R</kbd> Орудие</span><span class="extra"><kbd>T</kbd> Заправщик</span><span class="fps">'+Math.round(fps)+' FPS · '+(padDetected?'GAMEPAD':settings.quality.toUpperCase())+'</span></div>';
 if(me.landed&&!me.dead)html+='<div class="port-actions"><div class="eyebrow">ПОРТ / '+n.planet.name.toUpperCase()+'</div><h3>'+n.planet.port+'</h3><p>'+(me.scan?'Идёт поиск тайника: '+Math.ceil(me.scan)+' с':me.scanCD?'Сканер готов через '+Math.ceil(me.scanCD)+' с':'Сканер готов. На этой планете тайники приносят '+Math.round(n.planet.reward*s.loot)+' CR.')+'</p><button class="primary" data-game-action="scan">'+(me.scan?'Сканирование…':'Найти тайник')+' <kbd>F</kbd></button><button data-panel="hangar">Открыть ангар <kbd>K</kbd></button><button data-game-action="land">Взлететь <kbd>E</kbd></button></div>';
 if(me.jump)html+='<div class="jump-overlay"><div class="eyebrow" style="justify-content:center">КВАНТОВЫЙ ДВИГАТЕЛЬ</div><h2>'+C.PLANETS.find(x=>x.id===me.jump.to).name.toUpperCase()+'</h2><p>До выхода на орбиту · '+Math.ceil(me.jump.left)+' с</p><div class="jump-progress"><span style="width:'+((1-me.jump.left/6)*100)+'%"></span></div></div>';
 if(me.dead)html+='<div class="jump-overlay"><h2>СИГНАЛ ПОТЕРЯН</h2><p>Страховой корабль прибудет через '+Math.ceil(me.dead)+' с</p></div>';
 if(mode==='multi'&&(networkState==='lost'||performance.now()-lastSnapshot>5000))html+='<div class="lost-connection"><h3>Связь с сервером прервана</h3><p>Корабль остаётся в комнате. Попробуй подключиться снова.</p><button id="reconnect" class="primary">Переподключиться</button><button id="leave-server">В меню</button></div>';
 html+='<div class="touch-controls"><div><button data-touch="yawL" aria-label="Повернуть влево">←</button><button data-touch="forward" aria-label="Тяга">↑</button><button data-touch="yawR" aria-label="Повернуть вправо">→</button><button data-touch="pitchU" aria-label="Нос вверх">↥</button><button data-touch="brake" aria-label="Тормоз">X</button><button data-touch="pitchD" aria-label="Нос вниз">↧</button></div><div><button data-game-action="land">E</button><button data-game-action="selectWeapon">R</button><button data-touch="fire">◎</button></div></div>';
 // Preserve held touch controls across telemetry refreshes.
 const controls=$('.touch-controls');if(controls)controls.remove();$('#hud').innerHTML=html;if(controls){$('.touch-controls').replaceWith(controls);}document.querySelectorAll('[data-game-action]').forEach(b=>b.onclick=()=>act({type:b.dataset.gameAction}));document.querySelectorAll('[data-touch]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.touch]=true;};b.onpointerup=b.onpointercancel=()=>touch[b.dataset.touch]=false;});if($('#reconnect'))$('#reconnect').onclick=()=>connect(sessionResume);if($('#leave-server'))$('#leave-server').onclick=returnMenu;
}
function updateTargets(){if(!$('#targets')||!p())return;const me=p();let html='';for(const e of [...world.enemies,...Object.values(world.players).filter(x=>x.id!==myId)]){if(e.dead||e.landed||e.jump)continue;const distance=C.dist(e.p,me.p);if(distance>2000)continue;const marker=renderer.project(e.p);if(!marker.visible)continue;const friend=!e.id.startsWith('npc')&&!world.pvp;html+='<div class="target-box '+(friend?'friendly':'')+'" style="left:'+marker.x+'px;top:'+marker.y+'px"><div class="diamond"></div><div class="target-name">'+escape(e.name)+'</div><div class="target-life"><span style="width:'+C.clamp(e.hull/(e.maxHull||C.stats(e).hull)*100,0,100)+'%"></span></div>'+formatDistance(distance)+'</div>';}$('#targets').innerHTML=html;}
function keyAction(code){if(mode==='menu')return;const actions={KeyE:'land',KeyF:'scan',KeyT:'rescue',KeyR:'selectWeapon'};if(actions[code])act({type:actions[code]});if(code==='Digit1'&&p()?.active!==0)act({type:'selectWeapon'});if(code==='Digit2'&&p()?.active!==1)act({type:'selectWeapon'});if(code==='KeyM')mapPanel();if(code==='KeyK')hangarPanel();if(code==='F1'||code==='Slash')helpPanel();}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Escape'){if(document.pointerLockElement)return;if(currentPanel)closePanel();else if(mode!=='menu')pausePanel();return;}if(currentPanel)return;if(mode!=='menu'&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab','F1'].includes(e.code))e.preventDefault();if(!keys[e.code]&&!e.repeat)keyAction(e.code);keys[e.code]=true;});window.addEventListener('keyup',e=>{keys[e.code]=false;});window.addEventListener('blur',()=>{keys={};touch={};mouseFire=false;if(mode==='solo'&&!currentPanel)pausePanel();});
$('#space').addEventListener('mousedown',e=>{if(mode==='menu'||currentPanel||e.button!==0)return;audioStart();if(document.pointerLockElement)mouseFire=true;else{try{const result=$('#space').requestPointerLock?.();result?.catch(()=>toast('Обзор мышью недоступен. Используй стрелки клавиатуры.'));}catch{toast('Используй стрелки для поворота.');}}});window.addEventListener('mouseup',()=>mouseFire=false);document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement){mouseFire=false;transientMouse={yaw:0,pitch:0};}});document.addEventListener('mousemove',e=>{if(document.pointerLockElement){transientMouse.yaw-=e.movementX*.026*settings.mouse;transientMouse.pitch-=e.movementY*.026*settings.mouse*(settings.invert?-1:1);}});document.addEventListener('contextmenu',e=>{if(mode!=='menu'&&!currentPanel)e.preventDefault();});
function input(){const down=k=>keys[k]?1:0;const i={thrust:down('KeyW')-down('KeyS')+(touch.forward?1:0),strafe:down('KeyD')-down('KeyA'),lift:down('KeyC')-down('ControlLeft')-down('ControlRight'),yaw:down('ArrowLeft')-down('ArrowRight')+transientMouse.yaw+(touch.yawL?1:0)-(touch.yawR?1:0),pitch:(down('ArrowUp')-down('ArrowDown'))*(settings.invert?-1:1)+transientMouse.pitch+(touch.pitchU?1:0)-(touch.pitchD?1:0),roll:down('KeyQ')-down('KeyZ'),boost:!!(keys.ShiftLeft||keys.ShiftRight),brake:!!keys.KeyX||!!touch.brake,fire:!!keys.Space||mouseFire||!!touch.fire};transientMouse.yaw*=.5;transientMouse.pitch*=.5;
 try{const pads=navigator.getGamepads?.()||[],pad=Array.from(pads).find(x=>x&&x.mapping==='standard');padDetected=!!pad;if(pad){const dead=x=>Math.abs(x)>.14?x:0,pressed=j=>pad.buttons[j]?.pressed,edge=j=>pressed(j)&&!padPrevious[j];i.strafe+=dead(pad.axes[0]);i.thrust-=dead(pad.axes[1]);i.yaw-=dead(pad.axes[2]);i.pitch-=dead(pad.axes[3])*(settings.invert?-1:1);i.fire||=!!pressed(7);i.brake||=!!pressed(6);i.boost||=!!pressed(5);i.lift+=(pressed(12)?1:0)-(pressed(13)?1:0);if(!currentPanel){if(edge(0))act({type:'land'});if(edge(3))act({type:'scan'});if(edge(2))act({type:'selectWeapon'});if(edge(1))act({type:'rescue'});if(edge(14))mapPanel();if(edge(15))hangarPanel();}if(edge(9))currentPanel?closePanel():pausePanel();padPrevious=pad.buttons.map(x=>x.pressed);}else padPrevious=[];}catch{}
 if(currentPanel||networkState==='lost')return {brake:true};return C.sanitizeInput(i);
}
window.addEventListener('gamepadconnected',()=>{padDetected=true;toast('Геймпад подключён. Раскладка доступна в инструктаже.');});
window.addEventListener('beforeunload',saveSolo);document.addEventListener('visibilitychange',()=>{if(document.hidden){saveSolo();keys={};mouseFire=false;if(mode==='solo'&&!currentPanel)pausePanel();}});
function interpolateWorld(){if(mode!=='multi'||!snapshotNow||!snapshotPrev)return world;const alpha=C.clamp((performance.now()-snapshotTime)/67,0,1);const entities=[...Object.values(snapshotNow.players),...snapshotNow.enemies],previous=new Map([...Object.values(snapshotPrev.players),...snapshotPrev.enemies].map(x=>[x.id,x]));const clones=entities.map(e=>{const old=previous.get(e.id);if(!old||old.landed!==e.landed||C.dist(old.p,e.p)>400)return e;let diff=e.yaw-old.yaw;while(diff>Math.PI)diff-=Math.PI*2;while(diff<-Math.PI)diff+=Math.PI*2;return {...e,p:C.add(C.mul(old.p,1-alpha),C.mul(e.p,alpha)),yaw:old.yaw+diff*alpha,pitch:old.pitch+(e.pitch-old.pitch)*alpha};});return {...snapshotNow,players:Object.fromEntries(clones.filter(x=>snapshotNow.players[x.id]).map(x=>[x.id,x])),enemies:clones.filter(x=>!snapshotNow.players[x.id])};}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;const control=mode==='menu'?{}:input();accumulator+=dt;
 if(mode==='solo'&&!currentPanel){while(accumulator>=1/60){C.tick(world,{[myId]:control},1/60);accumulator-=1/60;}saveTimer+=dt;if(saveTimer>5){saveSolo();saveTimer=0;}}
 else{accumulator=0;if(mode==='menu')world.t+=dt;}
 if(mode==='multi'&&ws?.readyState===1&&networkState==='online'){netTimer+=dt;if(netTimer>=1/30){ws.send(JSON.stringify({type:'input',input:control}));netTimer=0;}}
 if(p()&&mode!=='menu'){if(control.fire&&p().cool>0&&now-lastShot>120){beep();lastShot=now;}if(engineGain){engineGain.gain.setTargetAtTime(!currentPanel&&!p().landed&&!p().dead&&!p().jump?settings.sound*.035*Math.min(C.len(p().v)/100,1):0,audioCtx.currentTime,.1);engineOsc.frequency.setTargetAtTime(30+Math.min(C.len(p().v),250)*.25,audioCtx.currentTime,.2);}observe();}
 drawTimer+=dt;const interval=1/settings.limit;if(drawTimer>=interval-.001){fps=fps*.95+(1/(drawTimer||interval))*.05;const renderWorld=interpolateWorld();renderer.update(renderWorld,renderWorld.players[myId],drawTimer,mode==='menu'?'menu':'game');drawTimer=0;updateTargets();}
 uiTime+=dt;if(uiTime>.16){drawHUD();uiTime=0;}
}
let uiTime=0;requestAnimationFrame(frame);
})();
