/* VESPER simulation. One deterministic ruleset for solo and authoritative server. */
(function(root){
'use strict';
const PLANETS=[
 {id:'aurora',name:'Аврора',type:'Океанический мир',p:[0,0,0],r:520,color:'#61bec7',kind:0,reward:220,port:'Новая гавань'},
 {id:'ember',name:'Эмбер',type:'Вулканическая планета',p:[5600,400,-4100],r:410,color:'#ec8556',kind:1,reward:310,port:'Терминал «Искра»'},
 {id:'nix',name:'Никс',type:'Ледяная граница',p:[-4800,1000,-5600],r:450,color:'#a7cce9',kind:2,reward:360,port:'Полярная станция'},
 {id:'dune',name:'Дюна',type:'Кольцевой пустынный мир',p:[900,-600,-10500],r:620,color:'#d3b684',kind:3,reward:440,port:'Порт «Меридиан»'}
];
const WEAPONS={pulse:{name:'Импульсный лазер',short:'ЛАЗЕР',price:0,damage:13,cool:.23,speed:820,life:1.8,ammo:null,color:'#77f6ee'},cannon:{name:'Рельсовая пушка',short:'ПУШКА',price:180,damage:35,cool:.62,speed:1050,life:1.8,ammo:'shell',color:'#ffd695'},plasma:{name:'Плазмомёт',short:'ПЛАЗМА',price:320,damage:24,cool:.4,speed:570,life:2.2,ammo:'plasma',color:'#be97ff'},scatter:{name:'Картечная пушка',short:'КАРТЕЧЬ',price:250,damage:11,cool:.8,speed:650,life:.8,ammo:'shell',color:'#f89867'}};
const MODULES={engine:{name:'Двигатель',price:140,description:'+14 м/с · ускорение'},tank:{name:'Топливный бак',price:100,description:'+50 единиц топлива'},armor:{name:'Бронеплита',price:120,description:'+50 прочности корпуса'},shield:{name:'Щитовой модуль',price:160,description:'+35 ёмкости щита'},cargo:{name:'Грузовой модуль',price:90,description:'+25% к находкам'}};
const SLOTS=['Левый пилон','Правый пилон','Левый борт','Правый борт','Кормовой отсек','Верхняя палуба'];
const DECALS=['none','comet','chevron','skull','sun'];
const COLORS=['#dce4e5','#df8554','#67bfc9','#a797d2','#a9bd74'];
const has=(obj,key)=>typeof key==='string'&&Object.prototype.hasOwnProperty.call(obj,key);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const add=(a,b)=>a.map((v,i)=>v+b[i]); const sub=(a,b)=>a.map((v,i)=>v-b[i]);const mul=(a,k)=>a.map(v=>v*k);const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);const len=a=>Math.hypot(...a);const norm=a=>mul(a,1/(len(a)||1));const dist=(a,b)=>len(sub(a,b));
function basis(yaw,pitch){return {f:[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],r:[Math.cos(yaw),0,-Math.sin(yaw)]};}
function stats(p){const n=k=>p.modules.filter(x=>x===k).length;return {hull:100+n('armor')*50,shield:60+n('shield')*35,fuel:100+n('tank')*50,speed:105+n('engine')*14,accel:40+n('engine')*12,loot:1+n('cargo')*.25};}
function createPlayer(id,name){return {id,name:String(name||'Странник').slice(0,20),p:[0,100,1100],v:[0,0,0],yaw:0,pitch:0,roll:0,hull:150,shield:60,fuel:150,credits:650,ammo:{shell:100,plasma:60},modules:['engine','engine','tank','armor',null,null],parts:{engine:100,weapons:100,reactor:100},weapons:['pulse','cannon'],owned:['pulse','cannon'],active:0,color:COLORS[0],decal:'comet',landed:null,jump:null,rescue:0,scan:0,scanCD:0,cool:0,heat:0,shieldDelay:0,dead:0,kills:0,finds:0,visited:[],notice:'Добро пожаловать. E — посадка на Аврору, M — карта системы.',noticeSeq:1,invulnerable:8};}
function createWorld(){const w={version:1,t:0,next:1,players:{},enemies:[],bullets:[],effects:[],pvp:false};for(let i=0;i<PLANETS.length;i++){const p=PLANETS[i];for(let j=0;j<2;j++)w.enemies.push({id:'npc-'+i+'-'+j,name:j?'Корсар':'Рейдер',home:i,p:add(p.p,[900+j*210,240+j*90,750]),v:[0,0,0],yaw:0,pitch:0,hull:75+i*20,maxHull:75+i*20,shield:25,cool:2+j,dead:0,target:null,color:'#a85148',modules:['engine','engine',null,null,null,null],weapons:['pulse','pulse'],decal:'skull'});}return w;}
function notice(p,s){p.notice=s;p.noticeSeq=(p.noticeSeq||0)+1;return false;}
function nearest(p){return PLANETS.map(x=>({planet:x,alt:dist(p.p,x.p)-x.r})).sort((a,b)=>a.alt-b.alt)[0];}
function landPosition(pl){return add(pl.p,[0,pl.r+7,0]);}
function action(w,id,a){const p=w.players[id];if(!p||!a||p.dead)return false;const st=stats(p);if(p.jump&&a.type!=='rescue')return notice(p,'Дождись выхода из квантового перехода.');
 if(a.type==='selectWeapon'){p.active=(p.active+1)%2;return true;}
 if(a.type==='land'){
  if(p.landed){if(p.fuel<=0)return notice(p,'Бак пуст. Заправь корабль в порту.');if(p.parts.engine<=0)return notice(p,'Двигатель сломан. Нужен ремонт.');const pl=PLANETS.find(x=>x.id===p.landed);p.p=add(pl.p,[0,120,pl.r+480]);p.v=[0,0,0];p.yaw=Math.PI;p.pitch=0;p.landed=null;p.invulnerable=6;return notice(p,'Взлёт завершён. Удерживай W, чтобы набрать скорость.');}
  const n=nearest(p);if(n.alt>700)return notice(p,'Посадка доступна в пределах 700 м от поверхности.');if(len(p.v)>70)return notice(p,'Снизь скорость до 70 м/с. X — тормоз.');p.landed=n.planet.id;p.p=landPosition(n.planet);p.v=[0,0,0];p.yaw=0;p.pitch=0;if(!p.visited.includes(p.landed)){p.visited.push(p.landed);p.credits+=100;notice(p,'Новый мир открыт: +100 CR. F — поиск тайников.');}else notice(p,'Посадка в '+n.planet.port+'. F — поиск тайников.');return true;
 }
 if(a.type==='jump'){const target=PLANETS.find(x=>x.id===a.planet);if(!target)return false;if(p.landed)return notice(p,'Сначала взлети: E.');if(p.fuel<22)return notice(p,'Для квантового перехода нужно 22 единицы топлива.');if(p.parts.engine<25||p.parts.reactor<25)return notice(p,'Для перехода почини двигатель и реактор до 25%.');if(nearest(p).planet.id===target.id&&nearest(p).alt<1800)return notice(p,'Ты уже на орбите этого мира.');p.fuel-=22;p.jump={to:target.id,left:6,total:6,from:p.p.slice()};p.v=[0,0,0];return notice(p,'Квантовый переход → '+target.name+'.');}
 if(a.type==='rescue'){if(p.rescue)return notice(p,'Заправщик уже в пути.');if(p.landed)return notice(p,'В порту топливо доступно в ангаре.');if(p.fuel>10&&p.parts.engine>0)return notice(p,'Аварийная помощь доступна при топливе ≤10 или поломке двигателя.');p.rescue=10;return notice(p,'Заправщик вылетел. 10 секунд. Стоимость 80 CR; при нехватке — бесплатно.');}
 if(a.type==='scan'){if(!p.landed)return notice(p,'Тайники ищут после посадки на планету.');if(p.scan>0||p.scanCD>0)return notice(p,'Сканер перезаряжается.');p.scan=5;return notice(p,'Поиск тайника: 5 секунд.');}
 if(a.type==='recover'){return false;}
 if(!p.landed)return notice(p,'Для обслуживания и сборки приземлись: E.');
 if(a.type==='buy'){
  if(a.item==='fuel'){const amount=Math.min(50,st.fuel-p.fuel);const cost=Math.ceil(amount);if(amount<.1)return notice(p,'Бак уже полон.');if(p.credits<cost)return notice(p,'Недостаточно CR. F — поиск тайников.');p.credits-=cost;p.fuel=Math.min(st.fuel,p.fuel+amount);return notice(p,'Заправлено '+Math.round(amount)+' ед. топлива.');}
  if(a.item==='repair'){const cost=Math.ceil((st.hull-p.hull)*.35+(300-p.parts.engine-p.parts.weapons-p.parts.reactor)*.2);if(!cost)return notice(p,'Корабль исправен.');if(p.credits<cost)return notice(p,'Не хватает '+(cost-p.credits)+' CR. Найди тайник: F.');p.credits-=cost;p.hull=st.hull;p.shield=st.shield;p.parts={engine:100,weapons:100,reactor:100};return notice(p,'Корпус и все системы восстановлены.');}
  if(a.item==='shell'||a.item==='plasma'){const cost=a.item==='shell'?60:80;if(p.credits<cost)return notice(p,'Недостаточно CR.');if(p.ammo[a.item]>=500)return notice(p,'Боезапас заполнен: 500.');p.credits-=cost;p.ammo[a.item]=Math.min(500,p.ammo[a.item]+50);return notice(p,'Боезапас пополнен на 50.');}
 }
 if(a.type==='weapon'&&has(WEAPONS,a.weapon)&&Number.isInteger(a.slot)&&a.slot>=0&&a.slot<2){if(!p.owned.includes(a.weapon)){const cost=WEAPONS[a.weapon].price;if(p.credits<cost)return notice(p,'Недостаточно CR.');p.credits-=cost;p.owned.push(a.weapon);}p.weapons[a.slot]=a.weapon;return notice(p,'Орудие установлено в слот '+(a.slot+1)+'.');}
 if(a.type==='module'&&Number.isInteger(a.slot)&&a.slot>=0&&a.slot<6&&(a.module===null||has(MODULES,a.module))){const old=p.modules[a.slot],next=a.module;if(old===next)return false;const cost=next?MODULES[next].price:0,refund=old?Math.floor(MODULES[old].price*.5):0;if(p.credits+refund<cost)return notice(p,'Недостаточно CR для модуля.');p.credits+=refund-cost;p.modules[a.slot]=next;const s=stats(p);p.hull=clamp(p.hull+(s.hull-st.hull),1,s.hull);p.shield=Math.min(p.shield,s.shield);p.fuel=Math.min(p.fuel,s.fuel);return notice(p,next?'Модуль установлен.':'Модуль снят. Возврат '+refund+' CR.');}
 if(a.type==='paint'&&COLORS.includes(a.color)){p.color=a.color;return true;}
 if(a.type==='decal'&&DECALS.includes(a.decal)){p.decal=a.decal;return true;}
 return false;
}
function fire(w,p,npc=false){const key=npc?'pulse':p.weapons[p.active];const spec=WEAPONS[key];if(p.cool>0||p.dead||p.landed||p.jump||(!npc&&(p.parts.weapons<=0||p.parts.reactor<=0||p.heat>92)))return false;if(!npc&&spec.ammo&&p.ammo[spec.ammo]<=0){if(!p.emptyWarn||w.t-p.emptyWarn>3){notice(p,'Боезапас пуст. Замени орудие: R, или купи снаряды в порту.');p.emptyWarn=w.t;}return false;}
 if(!npc){if(spec.ammo)p.ammo[spec.ammo]--;p.heat=Math.min(100,p.heat+(spec.ammo?5:13));}p.cool=spec.cool*(npc?4:1);const b=basis(p.yaw,p.pitch);let direction=b.f;
 // Mild aim assist inside a narrow 5-degree cone makes keyboard combat practical.
 if(!npc){let candidate=null,best=.995;for(const e of [...w.enemies,...(w.pvp?Object.values(w.players).filter(x=>x.id!==p.id):[])]){if(e.dead||e.landed||e.jump||dist(e.p,p.p)>1100)continue;const d=norm(sub(e.p,p.p)),alignment=dot(b.f,d);if(alignment>best){best=alignment;candidate=e;}}if(candidate)direction=norm(sub(add(candidate.p,mul(candidate.v||[0,0,0],dist(candidate.p,p.p)/spec.speed)),p.p));}
 const count=key==='scatter'?5:1;for(let i=0;i<count;i++){const spread=count===1?[0,0,0]:mul(b.r,(i-2)*.045);const d=norm(add(direction,spread));w.bullets.push({id:'b'+w.next++,owner:p.id,npc,p:add(p.p,mul(b.f,11)),v:mul(d,spec.speed),life:spec.life,damage:spec.damage,color:spec.color,key});}return true;
}
function hit(w,target,damage,owner){if(target.invulnerable>0||target.dead||target.landed||target.jump)return;target.shieldDelay=5;const shield=Math.min(target.shield||0,damage);target.shield=Math.max(0,(target.shield||0)-damage);const hullDamage=damage-shield;target.hull-=hullDamage;w.effects.push({id:'e'+w.next++,p:target.p.slice(),life:.45,color:'#ffae6f',size:4});if(target.parts&&hullDamage>0){const systems=['engine','weapons','reactor'];const k=systems[w.next%3];target.parts[k]=Math.max(0,target.parts[k]-hullDamage*2.4);if(target.parts[k]===0)notice(target,{engine:'Двигатель выведен из строя. T — аварийный ремонт.',weapons:'Оружие выведено из строя. Нужен ремонт в порту.',reactor:'Реактор выведен из строя. Щиты и оружие отключены.'}[k]);}
 if(target.hull<=0){target.hull=0;target.dead=target.parts?6:30;target.v=[0,0,0];w.effects.push({id:'e'+w.next++,p:target.p.slice(),life:1.4,color:'#ffb262',size:22});const killer=w.players[owner];if(killer&&killer.id!==target.id){killer.credits+=target.parts?100:180;killer.kills++;notice(killer,'Цель уничтожена. +'+(target.parts?100:180)+' CR.');}if(target.parts)notice(target,'Корабль потерян. Страховка доставит тебя в порт через 6 секунд.');}
}
function sanitizeInput(input){const v=x=>Number.isFinite(x)?clamp(x,-1,1):0;return {thrust:v(input?.thrust),strafe:v(input?.strafe),lift:v(input?.lift),yaw:v(input?.yaw),pitch:v(input?.pitch),roll:v(input?.roll),boost:!!input?.boost,brake:!!input?.brake,fire:!!input?.fire};}
function segmentDistance(a,b,p){const ab=sub(b,a),t=clamp(dot(sub(p,a),ab)/(dot(ab,ab)||1),0,1);return dist(add(a,mul(ab,t)),p);}
function tick(w,inputs,dt){dt=clamp(dt,0,.1);w.t+=dt;
 for(const p of Object.values(w.players)){
  if(p.dead>0){p.dead-=dt;if(p.dead<=0){p.dead=0;p.landed='aurora';p.p=landPosition(PLANETS[0]);p.hull=stats(p).hull;p.shield=stats(p).shield;p.parts={engine:100,weapons:100,reactor:100};p.fuel=Math.max(p.fuel,40);p.credits=Math.max(0,p.credits-100);p.jump=null;p.rescue=0;notice(p,'Страховка: корабль восстановлен. Сбор — до 100 CR.');}continue;}
  p.cool=Math.max(0,p.cool-dt);p.heat=Math.max(0,p.heat-dt*17);p.invulnerable=Math.max(0,(p.invulnerable||0)-dt);p.shieldDelay=Math.max(0,p.shieldDelay-dt);p.scanCD=Math.max(0,p.scanCD-dt);
  if(p.shieldDelay<=0&&p.parts.reactor>0)p.shield=Math.min(stats(p).shield,p.shield+dt*5*p.parts.reactor/100);
  if(p.rescue>0){p.rescue=Math.max(0,p.rescue-dt);if(p.rescue===0){p.credits=Math.max(0,p.credits-80);p.fuel=Math.min(stats(p).fuel,p.fuel+60);p.parts.engine=Math.max(p.parts.engine,50);notice(p,'Заправщик прибыл: +60 топлива, двигатель работает.');}}
  if(p.scan>0){p.scan=Math.max(0,p.scan-dt);if(p.scan===0&&p.landed){const pl=PLANETS.find(x=>x.id===p.landed),gain=Math.round(pl.reward*stats(p).loot);p.credits+=gain;p.finds++;p.scanCD=12;notice(p,'Тайник найден! +'+gain+' CR. Новый поиск через 12 секунд.');}}
  if(p.jump){p.jump.left=Math.max(0,p.jump.left-dt);const pl=PLANETS.find(x=>x.id===p.jump.to);const to=add(pl.p,[0,120,pl.r+500]),t=1-p.jump.left/p.jump.total;const ease=t*t*(3-2*t);p.p=add(mul(p.jump.from,1-ease),mul(to,ease));if(!p.jump.left){p.p=to;p.jump=null;p.yaw=0;p.pitch=0;p.invulnerable=5;notice(p,'Выход на орбиту '+pl.name+'. E — посадка.');}continue;}
  if(p.landed)continue;
  const i=sanitizeInput(inputs[p.id]||{}),s=stats(p),engine=s.accel*p.parts.engine/100;p.yaw+=i.yaw*dt*1.12;p.yaw=((p.yaw+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;p.pitch=clamp(p.pitch+i.pitch*dt*.9,-1.48,1.48);p.roll+=(i.roll*.65-i.yaw*.35-p.roll)*dt*5;
  const b=basis(p.yaw,p.pitch);if(p.fuel>0&&engine>0){const boost=i.boost?2.25:1;const acceleration=add(add(mul(b.f,i.thrust),mul(b.r,i.strafe*.75)),[0,i.lift*.75,0]);if(len(acceleration)>0){p.v=add(p.v,mul(norm(acceleration),dt*engine*boost));p.fuel=Math.max(0,p.fuel-dt*(i.boost?1.5:.42));}const max=s.speed*(i.boost?2.1:1);if(len(p.v)>max)p.v=mul(norm(p.v),max);p.v=mul(p.v,Math.max(0,1-dt*(i.brake?5:.13)));}
  else {p.v=[0,0,0];if(p.fuel<=0&&!p.fuelWarn){notice(p,'Топливо закончилось. Движение остановлено. T — вызвать заправщик.');p.fuelWarn=true;}}if(p.fuel>0)p.fuelWarn=false;
  if(p.fuel<=0)p.v=[0,0,0];p.p=add(p.p,mul(p.v,dt));if(len(p.p)>27000){p.p=mul(norm(p.p),26900);p.v=[0,0,0];notice(p,'Достигнута граница сектора. M — карта системы.');}
  for(const pl of PLANETS){const d=dist(p.p,pl.p);if(d<pl.r+12){const speed=len(p.v);p.p=add(pl.p,mul(norm(sub(p.p,pl.p)),pl.r+13));p.v=mul(p.v,-.2);if(speed>15)hit(w,p,Math.min(80,speed*.42),null);}}
  if(i.fire)fire(w,p);
 }
 for(const e of w.enemies){if(e.dead>0){e.dead-=dt;if(e.dead<=0){e.dead=0;e.hull=e.maxHull;e.shield=25;e.p=add(PLANETS[e.home].p,[1100,350,700]);}continue;}
  e.cool=Math.max(0,e.cool-dt);const targets=Object.values(w.players).filter(p=>!p.dead&&!p.landed&&!p.jump&&p.invulnerable<=0&&dist(p.p,e.p)<1500).sort((a,b)=>dist(e.p,a.p)-dist(e.p,b.p));const target=targets[0];e.target=target?.id||null;
  if(target){const d=sub(target.p,e.p),n=norm(d);e.yaw=Math.atan2(-n[0],-n[2]);e.pitch=Math.asin(clamp(n[1],-1,1));const range=len(d);e.v=mul(n,range>230?38:range<140?-25:0);e.p=add(e.p,mul(e.v,dt));if(range<900)fire(w,e,true);}else{const center=PLANETS[e.home].p,angle=w.t*.018+e.home+Number(e.id.slice(-1))*1.6;const next=add(center,[Math.cos(angle)*1100,300,Math.sin(angle)*1100]);e.v=mul(sub(next,e.p),.2);e.p=add(e.p,mul(e.v,dt));e.yaw=Math.atan2(-e.v[0],-e.v[2]);}
  const home=PLANETS[e.home],radial=sub(e.p,home.p);if(len(radial)<home.r+35)e.p=add(home.p,mul(norm(radial),home.r+35));
 }
 for(const b of w.bullets){const previous=b.p.slice();b.p=add(b.p,mul(b.v,dt));b.life-=dt;const possible=b.npc?Object.values(w.players):[...w.enemies,...(w.pvp?Object.values(w.players):[])];for(const target of possible){if(target.id===b.owner||target.dead||target.landed||target.jump)continue;if(segmentDistance(previous,b.p,target.p)<12){hit(w,target,b.damage,b.owner);b.life=0;break;}}if(PLANETS.some(pl=>segmentDistance(previous,b.p,pl.p)<pl.r))b.life=0;}
 w.bullets=w.bullets.filter(b=>b.life>0).slice(-800);w.effects.forEach(e=>e.life-=dt);w.effects=w.effects.filter(e=>e.life>0).slice(-100);
}
function snapshot(w){return JSON.parse(JSON.stringify(w));}
function restoreWorld(data){if(data?.version!==1||!data.players||typeof data.players!=='object')throw new Error('Несовместимое сохранение');const w=createWorld();w.t=Number.isFinite(data.t)?data.t:0;w.next=Number.isSafeInteger(data.next)?data.next:1;w.pvp=!!data.pvp;for(const [id,s] of Object.entries(data.players).slice(0,64)){const p=createPlayer(id,s.name);if(!Array.isArray(s.p)||s.p.length!==3||!s.p.every(Number.isFinite))continue;Object.assign(p,s);p.modules=Array.from({length:6},(_,i)=>has(MODULES,s.modules?.[i])?s.modules[i]:null);p.weapons=[0,1].map(i=>has(WEAPONS,s.weapons?.[i])?s.weapons[i]:'pulse');p.owned=Array.isArray(s.owned)?s.owned.filter(x=>has(WEAPONS,x)):['pulse'];p.credits=clamp(Number(s.credits)||0,0,10000000);p.landed=PLANETS.some(x=>x.id===s.landed)?s.landed:null;p.jump=null;p.rescue=0;p.scan=0;p.v=[0,0,0];p.invulnerable=8;w.players[id]=p;}return w;}
const api={PLANETS,WEAPONS,MODULES,SLOTS,DECALS,COLORS,clamp,add,sub,mul,dot,len,norm,dist,basis,stats,createPlayer,createWorld,action,tick,hit,fire,snapshot,restoreWorld,sanitizeInput,nearest,landPosition};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.VesperCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
