(function(){
'use strict';
const T=window.THREE,C=window.VesperCore;
const vec=a=>new T.Vector3(...a);
const noiseGLSL=`
float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float n=0.,a=.5;for(int i=0;i<5;i++){n+=noise(p)*a;p=p*2.03+vec3(7.2,3.9,5.1);a*=.5;}return n;}`;
const planetVert=`varying vec3 vN;varying vec3 vP;varying vec3 vWorld;void main(){vN=normalize(mat3(modelMatrix)*normal);vP=position;vWorld=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const planetFrag=`precision highp float;varying vec3 vN;varying vec3 vP;varying vec3 vWorld;uniform float kind;uniform float time;uniform vec3 tint;${noiseGLSL}
void main(){vec3 n=normalize(vP);float terrain=fbm(n*5.5+vec3(kind*4.,0,0));float detail=fbm(n*42.);vec3 sun=normalize(vec3(-.65,.45,.8));float lit=dot(normalize(vN),sun);vec3 water=vec3(.016,.08,.12);vec3 land=mix(vec3(.12,.23,.19),vec3(.43,.43,.31),detail);vec3 base;
if(kind<.5){base=mix(water,land,smoothstep(.48,.52,terrain));float ice=smoothstep(.84,.98,abs(n.y)+terrain*.12);base=mix(base,vec3(.64,.76,.78),ice);float clouds=smoothstep(.57,.73,fbm(n*8.+vec3(time*.001,0,0)));base=mix(base,vec3(.71,.78,.81),clouds*.8);}
else if(kind<1.5){base=mix(vec3(.09,.034,.021),vec3(.35,.13,.045),terrain);float lava=pow(max(0.,1.-abs(terrain-.5)*32.),5.);base+=vec3(1.8,.22,.01)*lava;}
else if(kind<2.5){base=mix(vec3(.18,.32,.44),vec3(.82,.9,.94),terrain);base*=.65+detail*.6;}
else{base=mix(vec3(.3,.15,.075),vec3(.81,.6,.34),terrain);base*=.8+.2*sin(n.y*130.+terrain*12.);}
float daylight=max(lit,0.);vec3 col=base*(.04+daylight*1.32);vec3 view=normalize(cameraPosition-vWorld);float rim=pow(1.-max(dot(normalize(vN),view),0.),3.5);col+=tint*rim*.46*smoothstep(-.3,.5,lit);float spec=pow(max(dot(reflect(-sun,normalize(vN)),view),0.),35.);if(kind<.5&&terrain<.48)col+=vec3(.25,.43,.5)*spec*.6;
gl_FragColor=vec4(col,1.);}`;
function disposeObject(group){group.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});}
function material(color,metal=.45,rough=.48){return new T.MeshStandardMaterial({color,metalness:metal,roughness:rough});}
function box(group,x,y,z,sx,sy,sz,mat){const m=new T.Mesh(new T.BoxGeometry(sx,sy,sz),mat);m.position.set(x,y,z);group.add(m);return m;}
function cylinder(group,x,y,z,r,h,mat,axis='z'){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,12),mat);if(axis==='z')m.rotation.x=Math.PI/2;m.position.set(x,y,z);group.add(m);return m;}
function plate(group,points,thickness,y,mat){const shape=new T.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const m=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:true,bevelThickness:.2,bevelSize:.2,bevelSegments:1,steps:1}),mat);m.rotation.x=Math.PI/2;m.position.y=y;group.add(m);return m;}
function decalTexture(kind){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const g=canvas.getContext('2d');g.fillStyle='#122a30';g.strokeStyle='#122a30';g.lineWidth=9;g.lineCap='square';
 if(kind==='chevron'){g.beginPath();g.moveTo(24,35);g.lineTo(64,75);g.lineTo(104,35);g.stroke();g.beginPath();g.moveTo(24,65);g.lineTo(64,105);g.lineTo(104,65);g.stroke();}
 if(kind==='comet'){g.beginPath();g.arc(78,79,21,0,Math.PI*2);g.fill();g.beginPath();g.moveTo(72,72);g.lineTo(19,14);g.lineTo(95,69);g.fill();g.lineWidth=4;g.beginPath();g.arc(64,64,49,.6,4.4);g.stroke();}
 if(kind==='skull'){g.beginPath();g.arc(64,53,34,0,Math.PI*2);g.fill();g.fillRect(42,69,44,28);g.clearRect(44,46,13,15);g.clearRect(73,46,13,15);g.clearRect(60,76,8,27);}
 if(kind==='sun'){g.beginPath();g.arc(64,64,23,0,7);g.fill();for(let i=0;i<8;i++){const a=i*Math.PI/4;g.beginPath();g.moveTo(64+Math.cos(a)*34,64+Math.sin(a)*34);g.lineTo(64+Math.cos(a)*50,64+Math.sin(a)*50);g.stroke();}}
 const tx=new T.CanvasTexture(canvas);tx.colorSpace=T.SRGBColorSpace;return tx;
}
function makeShip(p){const group=new T.Group(),hull=material(p.color||'#c8d4db'),dark=material('#18232e',.75,.3),trim=material('#8d9da7',.8,.3),glass=new T.MeshStandardMaterial({color:'#092732',metalness:.7,roughness:.16,emissive:'#115566',emissiveIntensity:.25}),glow=new T.MeshBasicMaterial({color:p.id?.startsWith('npc')?'#ff845d':'#8af8ee'});
 plate(group,[[0,-10],[2.2,-4],[3.1,5],[0,8],[-3.1,5],[-2.2,-4]],2,1,hull);
 plate(group,[[-1.1,-6],[1.1,-6],[1.5,0],[-1.5,0]],1.15,2,glass);
 plate(group,[[-2,0],[-8,4],[-8,6],[-2,5]],.5,0,hull);plate(group,[[2,0],[8,4],[8,6],[2,5]],.5,0,hull);
 box(group,0,.4,5,3,1,2.4,dark);box(group,0,1.4,4,.28,.25,4,trim);
 for(const side of [-1,1]){box(group,side*2.45,1.3,1,.22,.15,6,trim);box(group,side*7.3,.2,5,.7,.3,.7,glow);}
 const flames=[];const loc=[[-4.4,0,3.4],[4.4,0,3.4],[-4.3,.6,-.3],[4.3,.6,-.3],[0,1.6,5.7],[0,2.3,2]];
 for(let i=0;i<6;i++){const module=p.modules?.[i];if(!module)continue;const [x,y,z]=loc[i];
  if(module==='engine'){box(group,x,y,z,2.4,2.4,5.4,dark);box(group,x,y+1.25,z,2.4,.22,3,hull);cylinder(group,x,y,z+3,1,1.3,trim);cylinder(group,x,y,z+3.75,.76,.12,glow);const flame=new T.Mesh(new T.ConeGeometry(.72,6,12),new T.MeshBasicMaterial({color:'#72e6f9',transparent:true,opacity:.65,depthWrite:false}));flame.rotation.x=Math.PI/2;flame.position.set(x,y,z+6.6);group.add(flame);flames.push(flame);}
  if(module==='tank'){cylinder(group,x,y,z,1.25,4.7,trim);for(const zz of [-1.6,1.6])cylinder(group,x,y,z+zz,1.3,.24,dark);}
  if(module==='armor'){box(group,x,y,z,2.8,1.3,4.6,hull);for(const zz of [-1,0,1])box(group,x,y+.7,z+zz,2.4,.14,.2,trim);}
  if(module==='shield'){const m=new T.Mesh(new T.SphereGeometry(1.5,12,8),glass);m.scale.y=.65;m.position.set(x,y,z);group.add(m);cylinder(group,x,y-.7,z,1.5,.3,trim,'y');}
  if(module==='cargo'){box(group,x,y,z,2.8,2.6,3.6,material('#a98655'));for(const xx of [-1,1])box(group,x+xx,y,z,.2,2.7,3.8,dark);}
 }
 for(let i=0;i<2;i++){const x=i?2.45:-2.45,z=-5.2,key=p.weapons?.[i]||'pulse';box(group,x,-.9,z,1,.8,2,dark);cylinder(group,x,-.9,z-1.9,key==='plasma'?.48:.26,key==='cannon'?4:2,trim);if(key==='scatter'){for(const dx of [-.28,.28])cylinder(group,x+dx,-.9,z-2,.18,2,trim);}cylinder(group,x,-.9,z-2.95,.25,.2,new T.MeshBasicMaterial({color:C.WEAPONS[key].color}));}
 if(p.decal&&p.decal!=='none'){const m=new T.Mesh(new T.PlaneGeometry(2.1,2.1),new T.MeshBasicMaterial({map:decalTexture(p.decal),transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));m.rotation.x=-Math.PI/2;m.position.set(0,1.24,4);group.add(m);for(const side of [-1,1]){const s=m.clone();s.material=m.material.clone();s.rotation.set(0,side*Math.PI/2,0);s.position.set(side*3.12,-.15,3);s.scale.setScalar(.9);group.add(s);}}
 group.userData.flames=flames;return group;
}
class Renderer{
 constructor(canvas){this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.setClearColor('#02050b');this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(57,1,.25,60000);this.camera.position.set(0,210,1550);this.planets=[];this.ships=new Map();this.projectileMeshes=new Map();this.effectMeshes=new Map();this.quality='medium';this.scale=.85;this.fps=60;this.lastP=null;this.preview=null;
 const sun=new T.DirectionalLight('#daeaff',3.2);sun.position.set(-800,600,900);this.scene.add(sun,new T.AmbientLight('#687f9e',1.5));this.createStars();this.createPlanets();this.menuShip=makeShip(C.createPlayer('showcase','VESPER'));this.scene.add(this.menuShip);this.resize();window.addEventListener('resize',()=>this.resize());}
 createStars(){let seed=721;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const pos=[],col=[];for(let i=0;i<3800;i++){const theta=rand()*Math.PI*2,z=rand()*2-1,r=24000+rand()*6000,s=Math.sqrt(1-z*z);pos.push(r*s*Math.cos(theta),r*z,r*s*Math.sin(theta));const lum=.3+rand()*.7;col.push(lum*.85,lum*.93,lum);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('color',new T.Float32BufferAttribute(col,3));this.stars=new T.Points(g,new T.PointsMaterial({size:1.6,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.85}));this.scene.add(this.stars);
 const nebula=new T.Mesh(new T.SphereGeometry(34000,24,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`precision highp float;varying vec3 v;${noiseGLSL} void main(){vec3 n=normalize(v);float band=pow(max(0.,1.-abs(n.y*.8+n.x*.4+.15)),12.);float clouds=fbm(n*9.);vec3 c=vec3(.002,.004,.012)+band*clouds*vec3(.015,.026,.038);gl_FragColor=vec4(c,1.);}`}));this.scene.add(nebula);
 const rocks=new T.InstancedMesh(new T.IcosahedronGeometry(1,0),material('#554a47',.15,.95),90),dummy=new T.Object3D();for(let i=0;i<90;i++){const a=rand()*Math.PI*2,r=1900+rand()*450;dummy.position.set(Math.cos(a)*r,rand()*160-80,Math.sin(a)*r);dummy.rotation.set(rand()*5,rand()*5,rand()*5);dummy.scale.setScalar(4+rand()*13);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);}this.scene.add(rocks);this.rocks=rocks;}
 createPlanets(){for(const pl of C.PLANETS){const group=new T.Group();group.position.copy(vec(pl.p));const mat=new T.ShaderMaterial({vertexShader:planetVert,fragmentShader:planetFrag,uniforms:{kind:{value:pl.kind},time:{value:0},tint:{value:new T.Color(pl.color)}}});const globe=new T.Mesh(new T.SphereGeometry(pl.r,72,48),mat);group.add(globe);
  const atm=new T.Mesh(new T.SphereGeometry(pl.r*1.027,48,32),new T.ShaderMaterial({side:T.BackSide,transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{tint:{value:new T.Color(pl.color)}},vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'precision highp float;varying vec3 n;varying vec3 v;uniform vec3 tint;void main(){float a=pow(1.-abs(dot(normalize(n),normalize(v))),3.);gl_FragColor=vec4(tint,a*.48);}'}));group.add(atm);
  if(pl.kind===3){const ring=new T.Mesh(new T.RingGeometry(pl.r*1.45,pl.r*2.02,180),new T.MeshBasicMaterial({color:'#957a55',side:T.DoubleSide,transparent:true,opacity:.2,depthWrite:false}));ring.rotation.x=1.26;ring.rotation.y=.3;group.add(ring);for(let i=0;i<4;i++){const thin=new T.Mesh(new T.RingGeometry(pl.r*(1.5+i*.13),pl.r*(1.51+i*.13),128),new T.MeshBasicMaterial({color:'#cdb283',side:T.DoubleSide,transparent:true,opacity:.18}));thin.rotation.copy(ring.rotation);group.add(thin);}}
  const port=new T.Group();port.position.set(0,pl.r+1,0);const base=material('#263744',.7,.65),edge=new T.MeshBasicMaterial({color:pl.color});cylinder(port,0,1,0,62,4,base,'y');const landingRing=new T.Mesh(new T.RingGeometry(22,22.8,64),edge);landingRing.rotation.x=-Math.PI/2;landingRing.position.y=3.05;port.add(landingRing);box(port,0,3.1,0,12,.1,1,edge);box(port,-5.5,3.1,0,1,.1,12,edge);box(port,5.5,3.1,0,1,.1,12,edge);
  for(let i=0;i<7;i++){const a=i/7*Math.PI*2,x=Math.cos(a)*47,z=Math.sin(a)*47;box(port,x,7,z,8,14,10,base);box(port,x,14.1,z,6,.2,7,edge);for(let j=0;j<3;j++)box(port,x,5+j*3,z+5.1,5,.5,.1,edge);}group.add(port);this.scene.add(group);this.planets.push({group,globe,atm,port,pl});}}
 setSettings(s){this.quality=s.quality||'medium';this.scale=Number(s.scale)||.85;this.camera.fov=Number(s.fov)||57;const counts={low:900,medium:2400,high:3800};this.stars.geometry.setDrawRange(0,counts[this.quality]);this.rocks.visible=this.quality!=='low';this.planets.forEach(p=>p.atm.visible=this.quality!=='low');this.resize();}
 resize(){const w=innerWidth,h=innerHeight,ratio=Math.min(devicePixelRatio||1,1.5)*this.scale;this.renderer.setPixelRatio(ratio);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 update(world,player,dt,mode='game'){
  const menu=mode==='menu';this.menuShip.visible=menu;const t=world.t;this.planets.forEach(({globe})=>{globe.material.uniforms.time.value=t;});
  if(menu){this.camera.position.set(40,220,1550);this.camera.lookAt(-430,60,0);this.menuShip.position.set(180,3,930);this.menuShip.rotation.set(.15,2.1,0);this.menuShip.scale.setScalar(2.2);this.menuShip.position.y+=Math.sin(performance.now()*.0004)*4;}
  else if(player){const q=new T.Quaternion().setFromEuler(new T.Euler(player.pitch,player.yaw,0,'YXZ'));let desired,look;
   if(player.landed){desired=vec(player.p).add(new T.Vector3(26,18,34));look=vec(player.p).add(new T.Vector3(0,1,0));this.camera.up.set(0,1,0);}
   else{desired=vec(player.p).add(new T.Vector3(0,6.4,25).applyQuaternion(q));look=vec(player.p).add(new T.Vector3(0,1.5,-38).applyQuaternion(q));this.camera.up.set(0,1,0);}
   if(!this.lastP||C.dist(this.lastP,player.p)>150||this.lastMode!==mode||this.lastLanded!==player.landed)this.camera.position.copy(desired);else this.camera.position.lerp(desired,1-Math.exp(-dt*8));this.camera.lookAt(look);this.lastP=player.p.slice();this.lastMode=mode;this.lastLanded=player.landed;
   this.stars.position.copy(vec(player.p));
  }
  const tankers=Object.values(world.players).filter(p=>p.rescue>0).map(p=>({id:'tanker-'+p.id,name:'Заправщик',p:C.add(p.p,[Math.max(25,p.rescue*p.rescue*5),15,10]),v:[-40,0,0],yaw:Math.PI/2,pitch:0,modules:['engine','engine','cargo','tank','tank','cargo'],weapons:['pulse','pulse'],color:'#dba64d',decal:'sun'}));
  const entities=menu?[]:[...Object.values(world.players),...world.enemies,...tankers],visible=new Set();for(const p of entities){if(p.dead||(!p.id?.startsWith('npc')&&p.id!==player?.id&&C.dist(p.p,player?.p||[0,0,0])>9000))continue;visible.add(p.id);const sig=JSON.stringify([p.color,p.modules,p.weapons,p.decal]);let entry=this.ships.get(p.id);if(!entry||entry.sig!==sig){if(entry){this.scene.remove(entry.mesh);disposeObject(entry.mesh);}const mesh=makeShip(p);entry={mesh,sig};this.ships.set(p.id,entry);this.scene.add(mesh);mesh.position.copy(vec(p.p));}
   entry.mesh.position.lerp(vec(p.p),p.id===player?.id?1:1-Math.exp(-dt*16));entry.mesh.rotation.set(p.pitch||0,p.yaw||0,p.roll||0,'YXZ');entry.mesh.userData.flames.forEach(f=>{f.visible=!p.landed&&!p.dead&&p.fuel!==0&&p.parts?.engine!==0;f.scale.y=.4+Math.min(C.len(p.v||[0,0,0])/90,1.8)+Math.sin(performance.now()*.06)*.08;});}
  for(const [id,e] of this.ships)if(!visible.has(id)){this.scene.remove(e.mesh);disposeObject(e.mesh);this.ships.delete(id);}
  this.syncEffects(world,menu);this.renderer.render(this.scene,this.camera);if(this.preview)this.updatePreview(dt);
 }
 syncEffects(w,menu){const present=new Set();for(const b of menu?[]:w.bullets){present.add(b.id);let m=this.projectileMeshes.get(b.id);if(!m){m=new T.Mesh(new T.CylinderGeometry(b.key==='plasma'?1.3:.22,b.key==='plasma'?1.3:.22,b.key==='plasma'?4:14,5),new T.MeshBasicMaterial({color:b.color}));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),vec(b.v).normalize());this.projectileMeshes.set(b.id,m);this.scene.add(m);}m.position.copy(vec(b.p));}for(const [id,m] of this.projectileMeshes)if(!present.has(id)){this.scene.remove(m);disposeObject(m);this.projectileMeshes.delete(id);}
  const seen=new Set();for(const e of menu?[]:w.effects){seen.add(e.id);let m=this.effectMeshes.get(e.id);if(!m){m=new T.Mesh(new T.IcosahedronGeometry(1,1),new T.MeshBasicMaterial({color:e.color,transparent:true,opacity:1,wireframe:e.size>10}));m.position.copy(vec(e.p));this.scene.add(m);this.effectMeshes.set(e.id,m);}m.scale.setScalar(e.size*(1.5-e.life*.5));m.material.opacity=Math.min(1,e.life*1.5);}for(const [id,m] of this.effectMeshes)if(!seen.has(id)){this.scene.remove(m);disposeObject(m);this.effectMeshes.delete(id);}}
 project(p){const q=vec(p).project(this.camera);const behind=vec(p).sub(this.camera.position).dot(this.camera.getWorldDirection(new T.Vector3()))<0;return {x:(q.x*.5+.5)*innerWidth,y:(-.5*q.y+.5)*innerHeight,visible:!behind&&q.z<1&&Math.abs(q.x)<.94&&Math.abs(q.y)<.85};}
 openPreview(canvas,p){this.closePreview();const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.outputColorSpace=T.SRGBColorSpace;renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(420,320,false);const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,420/320,.1,1000);camera.position.set(25,20,31);camera.lookAt(0,0,0);scene.add(new T.AmbientLight('#c9dff5',2));const sun=new T.DirectionalLight('#fff1df',4);sun.position.set(-12,25,15);scene.add(sun);const mesh=makeShip(p);scene.add(mesh);const grid=new T.GridHelper(45,15,'#3b6670','#172b32');grid.position.y=-4;scene.add(grid);this.preview={renderer,scene,camera,mesh,sig:JSON.stringify([p.color,p.modules,p.weapons,p.decal])};}
 updatePreview(dt){const p=this.preview;p.mesh.rotation.y+=dt*.22;p.renderer.render(p.scene,p.camera);}
 closePreview(){if(this.preview){disposeObject(this.preview.scene);this.preview.renderer.dispose();this.preview=null;}}
}
window.VesperRenderer=Renderer;
})();
